### PR TITLE
use longest option name

### PR DESCRIPTION
**Pull request by mr-c**
Bonus: marks non-required "store" arguments as `optional="true"`

### CODE REVIEW

**Comment by mr-c** [comment]
Also address https://github.com/erasche/gxargparse/issues/15

**Comment by erasche** [comment]
Oh, excellent!

**Comment by mr-c** [comment]
Oh, I was still hacking away :-) Should have marked this "[WIP]" :-)

Thanks! I'll issue another PR with additional commits.

**Comment by erasche** [comment]
Ah, okay. I'll hopefully set up travis + test cases in the coming week.

**Pull request merged**
