### PR TITLE
inherit from the real ArgumentParser

### PR DESCRIPTION
**Pull request by mr-c**
which simplifies the code and enables supporting the extension of
_VersionAction and adds output support for argparse.FileType

### CODE REVIEW

**Comment by bgruening** [comment]
This looks very nice! Thanks!

**Comment by mr-c** [comment]
:-)

This is from running gxargparse on top of `normalize-by-median.py` from the just released v2.0 of khmer.

**Comment by mr-c** [comment]
Biggest downside is that it collapses the namespace a bit; you all might want to put the gxargparse specific attributes under a single underline prefixed attribute to keep it cleaner.

**Comment by erasche** [comment]
Woah, people actually using this! I really do need to get around to finding time for more testing and feature implementatino of these libraries... 

@mr-c this is an absolutely excellent addition, inheriting is the proper behaviour, I don't know why I didn't do that in the first place.

**Comment by erasche** [comment]
I'll try and get some of the other requested improvements and cleaning done tomorrow (or maybe this weekend) and then push an updated version. Thanks again for the contribution.

**Comment by mr-c** [comment]
It was my pleasure! Will be great when this replaces handwritten tool descriptions :-)

**Pull request merged**
